.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml: populate nut-ddl.py even if not generated from .in template currently
Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml b/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml
--- a/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml
+++ b/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml
@@ -25,7 +25,7 @@ jobs:
           run: |
               cd ../nut-website && \
               autoreconf -ifv && \
-              ./configure && \
+              ./configure || echo "CONFIGURE FAILED, WILL TRY DIRECTLY" >&2 ; \
               if [ ! -s tools/nut-ddl.py ] && [ -s tools/nut-ddl.py.in ] ; then \
                   cp -pf tools/nut-ddl.py.in tools/nut-ddl.py ; \
               fi ; \
