.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml: only autoconf... nut-website if nut-ddl.py.in becomes a real template
Expecting that eventually like in NUT itself we might pick a particular
value of a @PYTHON@ interpreter; currently we do not.

Signed-off-by: Jim Klimov <jimklimov+nut@gmail.com>

diff --git a/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml b/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml
--- a/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml
+++ b/.github/workflows/02-make-check-workflow-with-nut-website-scripts.yml
@@ -23,9 +23,11 @@ jobs:
                 sudo apt install build-essential python3 make autoconf autoconf-archive automake libtool m4 pkg-config
         - name: prepare nut-website repo
           run: |
-              cd ../nut-website && \
-              autoreconf -ifv && \
-              ./configure || echo "CONFIGURE FAILED, WILL TRY DIRECTLY" >&2 ; \
+              cd ../nut-website || exit ; \
+              if grep -E '@[^@][^@]*@' ../tools/nut-ddl.py.in ; then \
+                  autoreconf -ifv && \
+                  ./configure || echo "CONFIGURE FAILED, WILL TRY DIRECTLY" >&2 ; \
+              fi ; \
               if [ ! -s tools/nut-ddl.py ] && [ -s tools/nut-ddl.py.in ] ; then \
                   cp -pf tools/nut-ddl.py.in tools/nut-ddl.py ; \
               fi ; \
